server:
  port: 9082
spring:
  application:
    name: "LoanService"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    mongodb:
      uri: "mongodb://${MONGO_USER:${MONGO_USER:loan_mongo_user}}:${MONGO_PASSWORD:${MONGO_PASSWORD:loan_mongo_pass}}@${MONGO_HOST:${MONGO_HOST:localhost}}:${MONGO_PORT:${MONGO_PORT:27018}}/${MONGO_DB:${MONGO_DB:credit_loan_mongo}}?authSource=admin"
logging:
  level:
    org.hibernate.SQL: "DEBUG"
adapter:
  restconsumer:
    timeout: 5000
    url: "${CUSTOMER_URL:http://localhost:9081}"
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
resilience4j:
  circuitbreaker:
    instances:
      testGet:
        registerHealthIndicator: true
        failureRateThreshold: 1
        slowCallRateThreshold: 1
        slowCallDurationThreshold: "1s"
        permittedNumberOfCallsInHalfOpenState: 1
        slidingWindowSize: 1
        minimumNumberOfCalls: 1
        waitDurationInOpenState: "1s"
      testPost:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
adapters:
  r2dbc:
    host: "${POSTGRES_HOST:localhost}"
    port: "${POSTGRES_PORT:5434}"
    database: "${POSTGRES_DB:credit_loan_db}"
    schema: "public"
    username: "${POSTGRES_USER:loan_user}"
    password: "${POSTGRES_PASSWORD:loan_pass}"
jwt:
  secret: "${SECRET_KEY:uO8lC2VhP3nZ6kF9Q1tWjR7yX5aT2sVb0mGhN8oJzK4cE6rLwBqD3pUyHfMxZaSd}"
  expiration: "${EXPIRATION:3600000}"
entrypoint:
  sqs:
    region: "us-east-1"
    endpoint: "http://localhost:4566"
    queueUrl: "http://localhost:4566/000000000000/sample"
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 10
    numberOfThreads: 1
