server:
  port: 9082
spring:
  application:
    name: "LoanService"
  devtools:
    add-properties: false
  profiles:
    include: null
  jpa:
    show-sql: ${SPRING_JPA_SHOW_SQL}
    properties:
      hibernate:
        format_sql: ${SPRING_JPA_FORMAT_SQL}
  data:
    mongodb:
      uri: ${ADAPTER_MONGODB_URI}
logging:
  level:
    org.hibernate.SQL: ${LOGGING_HIBERNATE_SQL}
adapter:
  restconsumer:
    timeout: ${RESTCONSUMER_TIMEOUT}
    url: ${RESTCONSUMER_URL}
  sqs:
    region: ${ADAPTER_SQS_NOTIFICATION_REGION}
    queueUrl: ${ADAPTER_SQS_NOTIFICATION_QUEUE_URL}
    endpoint: ${ADAPTER_SQS_NOTIFICATION_ENDPOINT}
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
resilience4j:
  circuitbreaker:
    instances:
      testGet:
        registerHealthIndicator: true
        failureRateThreshold: 1
        slowCallRateThreshold: 1
        slowCallDurationThreshold: "1s"
        permittedNumberOfCallsInHalfOpenState: 1
        slidingWindowSize: 1
        minimumNumberOfCalls: 1
        waitDurationInOpenState: "1s"
      testPost:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
cors:
  allowed-origins: ${CORS_ORIGIN_ALLOWED}
adapters:
  r2dbc:
    host: ${POSTGRES_HOST}
    port: ${POSTGRES_PORT}
    database: ${POSTGRES_DB}
    schema: ${POSTGRES_SCHEMA}
    username: ${POSTGRES_USER:loan_user}
    password: ${POSTGRES_PASSWORD}
jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: ${JWT_EXPIRATION}

entrypoint:
  sqs:
    region: "us-east-1"
    endpoint: "http://localhost:4566"
    queueUrl: "http://localhost:4566/000000000000/sample"
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 10
    numberOfThreads: 1
